// listsync-nuxt/components/layout/Sidebar.vue
<template>
  <aside :class="sidebarClasses">
    <!-- Logo / Header -->
    <div class="flex items-center justify-between px-6 py-6 border-b border-purple-500/20">
      <NuxtLink to="/" class="flex items-center gap-3 text-foreground hover:text-purple-400 transition-colors">
        <div class="flex items-center justify-center w-10 h-10 rounded-lg bg-purple-500/20">
          <component :is="ListIcon" :size="24" class="text-purple-400" />
        </div>
        <span v-if="!uiStore.sidebarCollapsed" class="text-xl font-bold titillium-web-bold">
          ListSync
        </span>
      </NuxtLink>

      <!-- Collapse Toggle (Desktop) -->
      <button
        v-if="!isMobile"
        type="button"
        class="p-2 rounded-lg hover:bg-white/5 transition-colors text-muted-foreground hover:text-foreground"
        @click="uiStore.toggleSidebar"
        :aria-label="uiStore.sidebarCollapsed ? 'Expand sidebar' : 'Collapse sidebar'"
      >
        <component :is="uiStore.sidebarCollapsed ? ChevronRightIcon : ChevronLeftIcon" :size="20" />
      </button>

      <!-- Close Button (Mobile) -->
      <button
        v-if="isMobile"
        type="button"
        class="p-2 rounded-lg hover:bg-white/5 transition-colors text-muted-foreground hover:text-foreground lg:hidden"
        @click="uiStore.closeMobileMenu"
        aria-label="Close menu"
      >
        <component :is="XIcon" :size="20" />
      </button>
    </div>

    <!-- Navigation -->
    <nav class="flex-1 px-3 py-6 space-y-1 overflow-y-auto custom-scrollbar">
      <NuxtLink
        v-for="item in navigation"
        :key="item.path"
        :to="item.path"
        :class="navItemClasses(item.path)"
        @click="handleNavClick"
      >
        <component :is="item.icon" :size="20" />
        <span v-if="!uiStore.sidebarCollapsed" class="flex-1">
          {{ item.label }}
        </span>
      </NuxtLink>
    </nav>

    <!-- Footer (System Status) -->
    <div class="px-3 py-4 border-t border-purple-500/20">
      <div :class="footerClasses">
        <div class="flex items-center gap-3">
          <div :class="statusDotClass" />
          <div v-if="!uiStore.sidebarCollapsed" class="flex-1 min-w-0">
            <p class="text-sm font-medium text-foreground">System Status</p>
            <p class="text-xs text-muted-foreground truncate">
              {{ systemStore.isHealthy ? 'All systems operational' : 'Issues detected' }}
            </p>
          </div>
        </div>
      </div>
    </div>
  </aside>
</template>

<script setup lang="ts">
import {
  LayoutDashboard as DashboardIcon,
  List as ListIcon,
  RefreshCw as SyncIcon,
  History as HistoryIcon,
  Settings as SettingsIcon,
  Database as DatabaseIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
  X as XIcon,
} from 'lucide-vue-next'

const route = useRoute()
const uiStore = useUIStore()
const systemStore = useSystemStore()

const isMobile = ref(false)

const navigation = [
  {
    label: 'Dashboard',
    path: '/',
    icon: DashboardIcon,
  },
  {
    label: 'Lists',
    path: '/lists',
    icon: ListIcon,
  },
  {
    label: 'Items',
    path: '/items',
    icon: DatabaseIcon,
  },
  {
    label: 'Sync',
    path: '/sync',
    icon: SyncIcon,
  },
  {
    label: 'Sync History',
    path: '/sync-history',
    icon: HistoryIcon,
  },
  {
    label: 'Settings',
    path: '/settings',
    icon: SettingsIcon,
  },
]

const sidebarClasses = computed(() => {
  const baseClasses = [
    'flex flex-col h-screen',
    'glass-sidebar',
    'transition-all duration-300',
  ]

  // Width classes
  if (uiStore.sidebarCollapsed) {
    baseClasses.push('w-20')
  } else {
    baseClasses.push('w-64')
  }

  // Mobile classes
  if (isMobile.value) {
    baseClasses.push(
      'fixed inset-y-0 left-0 z-40',
      'transform lg:transform-none',
      uiStore.mobileMenuOpen ? 'translate-x-0' : '-translate-x-full'
    )
  }

  return baseClasses.join(' ')
})

const navItemClasses = (path: string) => {
  const isActive = route.path === path || (path !== '/' && route.path.startsWith(path))
  
  const baseClasses = [
    'flex items-center gap-3 px-3 py-2.5 rounded-lg',
    'text-sm font-medium',
    'transition-all duration-200',
    'group',
  ]

  if (uiStore.sidebarCollapsed) {
    baseClasses.push('justify-center')
  }

  if (isActive) {
    baseClasses.push(
      'bg-purple-500/20',
      'text-purple-300',
      'border border-purple-500/30'
    )
  } else {
    baseClasses.push(
      'text-muted-foreground',
      'hover:bg-white/5',
      'hover:text-foreground',
      'border border-transparent'
    )
  }

  return baseClasses.join(' ')
}

const footerClasses = computed(() => {
  const baseClasses = [
    'p-3 rounded-lg',
    'bg-black/20',
    'border border-purple-500/10',
  ]

  if (uiStore.sidebarCollapsed) {
    baseClasses.push('flex justify-center')
  }

  return baseClasses.join(' ')
})

const statusDotClass = computed(() => {
  const baseClasses = ['w-2 h-2 rounded-full']
  
  if (systemStore.isHealthy) {
    baseClasses.push('bg-green-500 pulse-glow')
  } else {
    baseClasses.push('bg-red-500 animate-pulse')
  }

  return baseClasses.join(' ')
})

const handleNavClick = () => {
  if (isMobile.value) {
    uiStore.closeMobileMenu()
  }
}

// Check if mobile on mount and resize
const checkMobile = () => {
  if (process.client) {
    isMobile.value = window.innerWidth < 1024
  }
}

onMounted(() => {
  checkMobile()
  if (process.client) {
    window.addEventListener('resize', checkMobile)
    
    // Fetch system health
    systemStore.checkHealth()
  }
})

onUnmounted(() => {
  if (process.client) {
    window.removeEventListener('resize', checkMobile)
  }
})
</script>

// listsync-web/src/components/layout/sidebar.tsx
"use client"

import Link from "next/link"
import { usePathname } from "next/navigation"
import { useState, useEffect } from "react"
import { 
  Home, 
  List, 
  RefreshCw, 
  BarChart3, 
  Activity, 
  Settings,
  Menu,
  X,
  BarChart
} from "lucide-react"
import { Logo } from "@/components/ui/logo"

const navigation = [
  { name: "Dashboard", href: "/dashboard", icon: Home },
  { name: "Statistics", href: "/dashboard/statistics", icon: BarChart },
  { name: "Lists", href: "/dashboard/lists", icon: List },
  { name: "Sync", href: "/dashboard/sync", icon: RefreshCw },
  { name: "Analytics", href: "/dashboard/analytics", icon: BarChart3 },
  { name: "Activity", href: "/dashboard/activity", icon: Activity },
  { name: "Settings", href: "/dashboard/settings", icon: Settings },
]

export function Sidebar() {
  const pathname = usePathname()
  const [isCollapsed, setIsCollapsed] = useState(false)
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false)
  const [isMobile, setIsMobile] = useState(false)

  // Check if screen is mobile size
  useEffect(() => {
    const checkScreenSize = () => {
      setIsMobile(window.innerWidth < 768) // md breakpoint
    }
    
    checkScreenSize()
    window.addEventListener('resize', checkScreenSize)
    
    return () => window.removeEventListener('resize', checkScreenSize)
  }, [])

  // Close mobile menu when route changes
  useEffect(() => {
    setIsMobileMenuOpen(false)
  }, [pathname])

  // Desktop sidebar component
  const DesktopSidebar = () => (
    <div className={`glass-sidebar min-h-screen p-6 relative overflow-hidden transition-all duration-300 flex-shrink-0 ${
      isCollapsed ? 'w-20' : 'w-64'
    }`}>
      {/* Header with Toggle Button */}
      <div className="mb-8 relative">
        {!isCollapsed ? (
          <>
            <div className="flex items-center justify-between mb-1">
              <Logo size="sm" showText={true} className="flex-1" />
              <button
                onClick={() => setIsCollapsed(!isCollapsed)}
                className="p-2 rounded-lg glass-button hover:scale-105 transition-all duration-200 flex-shrink-0 ml-2"
                aria-label="Collapse sidebar"
              >
                <X className="h-4 w-4" style={{ color: '#9d34da' }} />
              </button>
            </div>
            <div className="flex items-center gap-2 ml-1">
              <div className="w-1 h-1 rounded-full bg-purple-400/60"></div>
              <p className="text-xs text-white/60 titillium-web-light tracking-wide uppercase">Web Interface</p>
            </div>
          </>
        ) : (
          <div className="flex flex-col items-center">
            {/* Collapsed logo */}
            <Logo size="sm" showText={false} className="mb-4" />
            <button
              onClick={() => setIsCollapsed(!isCollapsed)}
              className="p-2 rounded-lg glass-button hover:scale-105 transition-all duration-200"
              aria-label="Expand sidebar"
            >
              <Menu className="h-4 w-4" style={{ color: '#9d34da' }} />
            </button>
          </div>
        )}
      </div>

      {/* Navigation */}
      <nav className="space-y-2">
        {navigation.map((item) => {
          const isActive = pathname === item.href
          return (
            <Link
              key={item.name}
              href={item.href}
              className={`flex items-center rounded-lg transition-all duration-300 group ${
                isActive
                  ? "border shadow-lg"
                  : "hover:bg-white/10 hover:border hover:border-white/20"
              } ${isCollapsed ? 'justify-center p-3' : 'gap-3 px-4 py-3'}`}
              style={{
                backgroundColor: isActive ? 'rgba(157, 52, 218, 0.3)' : 'transparent',
                color: isActive ? '#ffffff' : 'rgba(255, 255, 255, 0.8)',
                borderColor: isActive ? 'rgba(157, 52, 218, 0.5)' : 'transparent',
                boxShadow: isActive ? '0 4px 20px rgba(157, 52, 218, 0.3)' : 'none'
              }}
              title={isCollapsed ? item.name : undefined}
            >
              <item.icon 
                className={`h-5 w-5 transition-colors ${
                  isActive ? "" : "group-hover:opacity-100"
                } ${isCollapsed ? 'flex-shrink-0' : ''}`}
                style={{
                  color: isActive ? '#bd73e8' : 'rgba(157, 52, 218, 0.6)'
                }}
              />
              {!isCollapsed && (
                <span className="font-medium titillium-web-semibold">{item.name}</span>
              )}
            </Link>
          )
        })}
      </nav>

      {/* Decorative gradient */}
      <div 
        className="absolute bottom-0 left-0 right-0 h-32 pointer-events-none"
        style={{
          background: 'linear-gradient(to top, rgba(157, 52, 218, 0.2) 0%, transparent 100%)'
        }}
      />
    </div>
  )

  // Mobile sidebar component
  const MobileSidebar = () => (
    <div className="w-64 glass-sidebar min-h-screen p-6 relative overflow-hidden">
      {/* Header */}
      <div className="mb-8 relative">
        <div className="flex items-center justify-between mb-1">
          <Logo size="sm" showText={true} className="flex-1" />
          <button
            onClick={() => setIsMobileMenuOpen(false)}
            className="p-2 rounded-lg glass-button hover:scale-105 transition-all duration-200 flex-shrink-0 ml-2"
            aria-label="Close menu"
          >
            <X className="h-4 w-4" style={{ color: '#9d34da' }} />
          </button>
        </div>
        <div className="flex items-center gap-2 ml-1">
          <div className="w-1 h-1 rounded-full bg-purple-400/60"></div>
          <p className="text-xs text-white/60 titillium-web-light tracking-wide uppercase">Web Interface</p>
        </div>
      </div>

      {/* Navigation */}
      <nav className="space-y-2">
        {navigation.map((item) => {
          const isActive = pathname === item.href
          return (
            <Link
              key={item.name}
              href={item.href}
              className={`flex items-center gap-3 px-4 py-3 rounded-lg transition-all duration-300 group ${
                isActive
                  ? "border shadow-lg"
                  : "hover:bg-white/10 hover:border hover:border-white/20"
              }`}
              style={{
                backgroundColor: isActive ? 'rgba(157, 52, 218, 0.3)' : 'transparent',
                color: isActive ? '#ffffff' : 'rgba(255, 255, 255, 0.8)',
                borderColor: isActive ? 'rgba(157, 52, 218, 0.5)' : 'transparent',
                boxShadow: isActive ? '0 4px 20px rgba(157, 52, 218, 0.3)' : 'none'
              }}
            >
              <item.icon 
                className="h-5 w-5 transition-colors group-hover:opacity-100"
                style={{
                  color: isActive ? '#bd73e8' : 'rgba(157, 52, 218, 0.6)'
                }}
              />
              <span className="font-medium titillium-web-semibold">{item.name}</span>
            </Link>
          )
        })}
      </nav>

      {/* Decorative gradient */}
      <div 
        className="absolute bottom-0 left-0 right-0 h-32 pointer-events-none"
        style={{
          background: 'linear-gradient(to top, rgba(157, 52, 218, 0.2) 0%, transparent 100%)'
        }}
      />
    </div>
  )

  if (isMobile) {
    return (
      <>
        {/* Mobile hamburger button */}
        <button
          onClick={() => setIsMobileMenuOpen(true)}
          className="fixed top-4 left-4 z-50 p-3 rounded-lg glass-button hover:scale-105 transition-all duration-200 md:hidden"
          aria-label="Open menu"
        >
          <Menu className="h-5 w-5" style={{ color: '#9d34da' }} />
        </button>

        {/* Mobile overlay */}
        {isMobileMenuOpen && (
          <>
            {/* Backdrop */}
            <div 
              className="fixed inset-0 bg-black/50 z-40 md:hidden"
              onClick={() => setIsMobileMenuOpen(false)}
            />
            
            {/* Mobile sidebar */}
            <div className="fixed top-0 left-0 z-50 h-full transform transition-transform duration-300 md:hidden">
              <MobileSidebar />
            </div>
          </>
        )}
      </>
    )
  }

  // Desktop version
  return <DesktopSidebar />
}
