// listsync-nuxt/components/dashboard/QuickActions.vue
<template>
  <Card variant="default" class="overflow-hidden relative">
    <!-- Subtle animated background -->
    <div class="absolute inset-0 bg-gradient-to-r from-purple-500/5 via-transparent to-accent/5 opacity-50" />
    
    <template #header>
      <h3 class="text-xl font-bold titillium-web-bold relative">Quick Actions</h3>
    </template>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 relative">
      <!-- Trigger Sync -->
      <button
        :class="[
          actionButtonClasses,
          syncStore.isSyncing 
            ? 'bg-purple-500/20 border-purple-500/50' 
            : 'hover:border-purple-500/40'
        ]"
        :disabled="syncStore.isSyncing"
        @click="handleTriggerSync"
      >
        <component 
          :is="syncStore.isSyncing ? LoaderIcon : RefreshCwIcon" 
          :size="18" 
          :class="syncStore.isSyncing ? 'animate-spin' : 'group-hover:rotate-90 transition-transform duration-300'" 
        />
        <span class="text-sm font-medium">
          {{ syncStore.isSyncing ? 'Syncing...' : 'Trigger Sync' }}
        </span>
      </button>

      <!-- Add List -->
      <button
        :class="[actionButtonClasses, 'hover:border-green-500/40']"
        @click="$router.push('/lists?action=add')"
      >
        <component :is="PlusCircleIcon" :size="18" class="group-hover:scale-110 transition-transform duration-300" />
        <span class="text-sm font-medium">Add List</span>
      </button>

      <!-- Sync History -->
      <button
        :class="[actionButtonClasses, 'hover:border-purple-500/40']"
        @click="$router.push('/sync-history')"
      >
        <component :is="HistoryIcon" :size="18" class="group-hover:scale-110 transition-transform duration-300" />
        <span class="text-sm font-medium">Sync History</span>
      </button>

      <!-- Settings -->
      <button
        :class="[actionButtonClasses, 'hover:border-amber-500/40']"
        @click="$router.push('/settings')"
      >
        <component :is="SettingsIcon" :size="18" class="group-hover:rotate-90 transition-transform duration-300" />
        <span class="text-sm font-medium">Settings</span>
      </button>
    </div>
  </Card>
</template>

<script setup lang="ts">
import {
  RefreshCw as RefreshCwIcon,
  PlusCircle as PlusCircleIcon,
  History as HistoryIcon,
  Settings as SettingsIcon,
  Loader2 as LoaderIcon,
} from 'lucide-vue-next'

const syncStore = useSyncStore()
const { showSuccess, showError } = useToast()

const actionButtonClasses = computed(() => {
  return [
    'flex items-center justify-center gap-2 px-4 py-3',
    'rounded-lg border border-purple-500/20',
    'bg-black/20',
    'hover:border-purple-500/50 hover:bg-purple-500/10',
    'active:scale-98',
    'transition-all duration-200',
    'text-foreground hover:text-purple-300',
    'disabled:opacity-50 disabled:cursor-not-allowed',
    'shadow-sm hover:shadow-lg hover:shadow-purple-500/10',
    'group',
  ].join(' ')
})

const handleTriggerSync = async () => {
  if (syncStore.isSyncing) return

  try {
    await syncStore.triggerSync()
    showSuccess('Sync Started', 'Your sync has been triggered successfully')
  } catch (error: any) {
    showError('Sync Failed', error.message || 'Failed to trigger sync')
  }
}
</script>

// listsync-web/src/components/dashboard/quick-actions.tsx
"use client"

import { Button } from "@/components/ui/button"
import { RotateCw, Plus, Settings, Activity, Zap, CheckCircle, AlertCircle } from "lucide-react"
import { useState } from "react"
import { apiClient } from "@/lib/api/client"
import { toast } from "sonner"

export function QuickActions() {
  const [isSyncing, setIsSyncing] = useState(false)
  const [syncSuccess, setSyncSuccess] = useState(false)

  const handleSyncNow = async () => {
    setIsSyncing(true)
    setSyncSuccess(false)
    
    try {
      // First check if we can trigger sync
      const syncStatus = await apiClient.getSyncProcessStatus()
      
      if (!syncStatus.can_trigger_sync) {
        toast.error("Cannot trigger sync", {
          description: "No ListSync process found. Please ensure ListSync is running in automated mode."
        })
        return
      }

      // Trigger the sync
      const result = await apiClient.triggerManualSync()
      
      if (result.success) {
        setSyncSuccess(true)
        toast.success("Sync triggered successfully!", {
          description: result.note
        })
        
        // Reset success state after 3 seconds
        setTimeout(() => setSyncSuccess(false), 3222)
      } else {
        toast.error("Failed to trigger sync", {
          description: "Check the console for more details"
        })
      }
    } catch (error) {
      console.error("Error triggering sync:", error)
      toast.error("Failed to trigger sync", {
        description: error instanceof Error ? error.message : "Unknown error occurred"
      })
    } finally {
      setIsSyncing(false)
    }
  }

  const handleAddList = () => {
    // TODO: Open add list modal
    toast.info("Add List feature coming soon!")
  }

  const handleViewActivity = () => {
    // Navigate to activity page
    window.location.href = "/dashboard/activity"
  }

  const handleSettings = () => {
    // TODO: Open settings modal
    toast.info("Settings feature coming soon!")
  }

  const actions = [
    {
      title: "Sync Now",
      description: isSyncing ? "Triggering sync..." : syncSuccess ? "Sync triggered!" : "Trigger immediate sync",
      icon: syncSuccess ? CheckCircle : RotateCw,
      onClick: handleSyncNow,
      variant: "outline" as const,
      disabled: isSyncing,
      loading: isSyncing,
      success: syncSuccess,
    },
    {
      title: "Add List",
      description: "Connect new watchlist",
      icon: Plus,
      onClick: handleAddList,
      variant: "outline" as const,
      disabled: false,
      loading: false,
      success: false,
    },
    {
      title: "View Activity",
      description: "Recent sync history",
      icon: Activity,
      onClick: handleViewActivity,
      variant: "outline" as const,
      disabled: false,
      loading: false,
      success: false,
    },
    {
      title: "Settings",
      description: "Configure ListSync",
      icon: Settings,
      onClick: handleSettings,
      variant: "outline" as const,
      disabled: false,
      loading: false,
      success: false,
    },
  ]

  return (
    <div className="glass-card p-6">
      <div className="flex items-center gap-3 mb-6">
        <div className="p-2 rounded-lg status-info">
          <Zap className="h-5 w-5" />
        </div>
        <div>
          <h3 className="text-xl font-semibold text-white titillium-web-semibold">
            Quick Actions
          </h3>
          <p className="text-sm titillium-web-light" style={{ color: 'rgba(255, 255, 255, 0.7)' }}>
            Manage your sync operations
          </p>
        </div>
      </div>
      
      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">
        {actions.map((action, index) => (
          <div
            key={action.title}
            className="group"
            style={{ animationDelay: `${index * 100}ms` }}
          >
            <Button 
              onClick={action.onClick}
              disabled={action.disabled}
              className={`w-full h-32 p-4 flex flex-col items-center justify-center gap-3 text-center transition-all duration-300 glass-button hover:scale-105 ${
                action.success ? 'border-green-500/50 bg-green-500/10' : ''
              } ${
                action.disabled ? 'opacity-50 cursor-not-allowed' : ''
              }`}
              variant={action.variant}
            >
              <div className={`p-3 rounded-lg transition-all duration-300 group-hover:scale-110 ${
                action.loading ? 'animate-spin' : ''
              } ${
                action.success ? 'bg-green-500/20 border-green-500/30' : 'bg-purple-500/20 border-purple-500/30'
              }`}
              style={{
                backgroundColor: action.success ? 'rgba(34, 197, 94, 0.2)' : 'rgba(157, 52, 218, 0.2)',
                borderColor: action.success ? 'rgba(34, 197, 94, 0.3)' : 'rgba(157, 52, 218, 0.3)'
              }}>
                <action.icon className={`h-5 w-5 ${
                  action.success ? 'text-green-400' : ''
                }`} />
              </div>
              
              <div className="space-y-1">
                <div className="font-medium text-sm titillium-web-semibold">
                  {action.title}
                </div>
                <div className="text-xs opacity-80 titillium-web-light"
                style={{
                  color: 'rgba(255, 255, 255, 0.8)'
                }}>
                  {action.description}
                </div>
              </div>
            </Button>
          </div>
        ))}
      </div>
    </div>
  )
}
