// listsync-nuxt/pages/recent-activity.vue
<template>
  <div class="space-y-6">
    <!-- Header -->
    <div class="flex flex-col md:flex-row md:items-center justify-between gap-4">
      <div>
        <h1 class="text-4xl font-bold text-foreground titillium-web-bold bg-gradient-to-r from-purple-400 to-purple-600 bg-clip-text text-transparent">
          Recent Activity
        </h1>
        <p class="text-muted-foreground mt-2 text-base">
          Latest sync activities and media processing
        </p>
      </div>
      <Button
        variant="ghost"
        size="sm"
        @click="navigateTo('/')"
      >
        ← Back to Dashboard
      </Button>
    </div>

    <!-- Stats Summary -->
    <div class="grid grid-cols-1 md:grid-cols-4 gap-3">
      <Card class="border border-purple-500/30 hover:border-purple-400/50 transition-all duration-300">
        <div class="p-3">
          <div class="flex items-center gap-2.5">
            <div class="p-2 rounded-lg bg-gradient-to-br from-purple-600/20 to-purple-500/10 border border-purple-500/30">
              <CheckCircle2Icon class="w-4 h-4 text-purple-400" />
            </div>
            <div>
              <p class="text-2xl font-bold text-foreground leading-none">{{ successCount }}</p>
              <p class="text-[10px] text-muted-foreground font-medium">Successful</p>
            </div>
          </div>
        </div>
      </Card>

      <Card class="border border-purple-500/30 hover:border-purple-400/50 transition-all duration-300">
        <div class="p-3">
          <div class="flex items-center gap-2.5">
            <div class="p-2 rounded-lg bg-gradient-to-br from-purple-500/18 to-purple-400/9 border border-purple-400/28">
              <XCircleIcon class="w-4 h-4 text-purple-300" />
            </div>
            <div>
              <p class="text-2xl font-bold text-foreground leading-none">{{ failedCount }}</p>
              <p class="text-[10px] text-muted-foreground font-medium">Failed</p>
            </div>
          </div>
        </div>
      </Card>

      <Card class="border border-purple-500/30 hover:border-purple-400/50 transition-all duration-300">
        <div class="p-3">
          <div class="flex items-center gap-2.5">
            <div class="p-2 rounded-lg bg-gradient-to-br from-purple-400/20 to-purple-300/10 border border-purple-300/30">
              <AlertCircleIcon class="w-4 h-4 text-purple-200" />
            </div>
            <div>
              <p class="text-2xl font-bold text-foreground leading-none">{{ notFoundCount }}</p>
              <p class="text-[10px] text-muted-foreground font-medium">Not Found</p>
            </div>
          </div>
        </div>
      </Card>

      <Card class="border border-purple-500/30 hover:border-purple-400/50 transition-all duration-300">
        <div class="p-3">
          <div class="flex items-center gap-2.5">
            <div class="p-2 rounded-lg bg-gradient-to-br from-purple-300/20 to-purple-200/10 border border-purple-200/30">
              <ActivityIcon class="w-4 h-4 text-purple-100" />
            </div>
            <div>
              <p class="text-2xl font-bold text-foreground leading-none">{{ activities.length }}</p>
              <p class="text-[10px] text-muted-foreground font-medium">Total Items</p>
            </div>
          </div>
        </div>
      </Card>
    </div>

    <!-- Filters -->
    <Card class="border border-purple-500/30 hover:border-purple-400/50 transition-all duration-300">
      <div class="p-3">
        <div class="flex flex-wrap items-center gap-2">
          <button
            v-for="filter in filters"
            :key="filter.value"
            :class="[
              'px-3 py-1.5 rounded-lg text-[10px] font-bold uppercase tracking-wide transition-all',
              selectedFilter === filter.value
                ? 'bg-purple-600/20 text-purple-300 border border-purple-500/30'
                : 'bg-purple-500/5 text-purple-400/70 border border-purple-500/10 hover:bg-purple-500/10 hover:text-purple-300 hover:border-purple-500/20'
            ]"
            @click="selectedFilter = filter.value"
          >
            {{ filter.label }}
          </button>
        </div>
      </div>
    </Card>

    <!-- Activity List -->
    <Card class="border border-purple-500/30 hover:border-purple-400/50 transition-all duration-300">
      <div class="divide-y divide-purple-500/10">
        <!-- Loading State -->
        <div v-if="loading" class="p-8 text-center">
          <div class="inline-flex items-center gap-2 text-muted-foreground">
            <div class="animate-spin rounded-full h-5 w-5 border-2 border-purple-500 border-t-transparent" />
            <span>Loading activities...</span>
          </div>
        </div>

        <!-- Empty State -->
        <div v-else-if="filteredActivities.length === 0" class="p-8 text-center">
          <ActivityIcon class="w-12 h-12 text-muted-foreground mx-auto mb-3 opacity-50" />
          <p class="text-muted-foreground">No activities found</p>
        </div>

        <!-- Activity Items -->
        <div
          v-for="(activity, index) in filteredActivities"
          :key="index"
          class="p-4 hover:bg-white/5 transition-colors"
        >
          <div class="flex items-center gap-4">
            <!-- Status Icon -->
            <div :class="['p-2 rounded-lg', getStatusBg(activity.status)]">
              <component :is="getStatusIcon(activity.status)" :class="['w-5 h-5', getStatusColor(activity.status)]" />
            </div>

            <!-- Content -->
            <div class="flex-1 min-w-0">
              <div class="flex items-center gap-2 mb-1">
                <p class="font-medium text-foreground truncate">{{ activity.title }}</p>
                <Badge v-if="activity.media_type" variant="secondary" class="text-xs">
                  {{ activity.media_type }}
                </Badge>
              </div>
              <p class="text-xs text-muted-foreground">
                {{ getActionText(activity.status) }}
              </p>
            </div>

            <!-- Time -->
            <div class="text-right">
              <TimeAgo :timestamp="activity.timestamp" class="text-xs text-muted-foreground" />
            </div>
          </div>
        </div>
      </div>

      <!-- Pagination -->
      <div v-if="filteredActivities.length > 0" class="p-4 border-t border-border">
        <div class="flex items-center justify-between">
          <p class="text-sm text-muted-foreground">
            Showing {{ filteredActivities.length }} of {{ activities.length }} activities
          </p>
          <Button
            v-if="activities.length > filteredActivities.length"
            variant="secondary"
            size="sm"
            @click="loadMore"
          >
            Load More
          </Button>
        </div>
      </div>
    </Card>
  </div>
</template>

<script setup lang="ts">
import {
  CheckCircle2 as CheckCircle2Icon,
  XCircle as XCircleIcon,
  AlertCircle as AlertCircleIcon,
  Activity as ActivityIcon,
  Film as FilmIcon,
  Tv as TvIcon,
} from 'lucide-vue-next'

interface Activity {
  title: string
  status: string
  timestamp: string
  media_type: string
}

const loading = ref(true)
const activities = ref<Activity[]>([])
const selectedFilter = ref<string>('all')

const filters = [
  { label: 'All', value: 'all' },
  { label: 'Success', value: 'success' },
  { label: 'Failed', value: 'failed' },
  { label: 'Not Found', value: 'not_found' },
  { label: 'Movies', value: 'movie' },
  { label: 'TV Shows', value: 'tv' },
]

// Fetch activities with pagination to get more than 20 items
const fetchActivities = async () => {
  loading.value = true
  try {
    const api = useApiService()
    let allActivities: any[] = []
    let currentPage = 1
    const pageSize = 20 // API max limit
    let hasMorePages = true
    
    // Fetch multiple pages to get more activities
    while (hasMorePages && currentPage <= 5) { // Max 5 pages = 100 activities
      const response = await api.getRecentActivity(pageSize, currentPage)
      
      let pageActivities: any[] = []
      if (response && Array.isArray(response.items)) {
        pageActivities = response.items
      } else if (response && Array.isArray(response)) {
        pageActivities = response
      }
      
      if (pageActivities.length === 0) {
        hasMorePages = false
      } else {
        allActivities = allActivities.concat(pageActivities)
        currentPage++
      }
    }
    
    activities.value = allActivities.map((activity: any) => ({
      title: activity.title || activity.media_title || 'Unknown',
      status: activity.status || 'unknown',
      timestamp: activity.timestamp || activity.synced_at || new Date().toISOString(),
      media_type: activity.media_type || 'movie',
    }))
    
    console.log(`Loaded ${activities.value.length} recent activities (${currentPage - 1} pages)`)
  } catch (error) {
    console.error('Error fetching activities:', error)
  } finally {
    loading.value = false
  }
}

// Computed
const filteredActivities = computed(() => {
  if (selectedFilter.value === 'all') {
    return activities.value
  }
  
  if (['movie', 'tv'].includes(selectedFilter.value)) {
    return activities.value.filter(a => a.media_type === selectedFilter.value)
  }
  
  return activities.value.filter(a => a.status === selectedFilter.value)
})

const successCount = computed(() => {
  const successStatuses = ['requested', 'already_available', 'already_requested', 'skipped', 'success']
  return activities.value.filter(a => successStatuses.includes(a.status.toLowerCase())).length
})

const failedCount = computed(() => {
  const failedStatuses = ['failed', 'error']
  return activities.value.filter(a => failedStatuses.includes(a.status.toLowerCase())).length
})

const notFoundCount = computed(() => 
  activities.value.filter(a => a.status.toLowerCase() === 'not_found').length
)

// Helper functions
const getStatusIcon = (status: string) => {
  const icons: Record<string, any> = {
    success: CheckCircle2Icon,
    failed: XCircleIcon,
    not_found: AlertCircleIcon,
    error: XCircleIcon,
  }
  return icons[status] || ActivityIcon
}

const getStatusColor = (status: string) => {
  return 'text-purple-400'
}

const getStatusBg = (status: string) => {
  const backgrounds: Record<string, string> = {
    success: 'bg-gradient-to-br from-purple-600/20 to-purple-500/10 border border-purple-500/30',
    failed: 'bg-gradient-to-br from-purple-500/18 to-purple-400/9 border border-purple-400/28',
    not_found: 'bg-gradient-to-br from-purple-400/20 to-purple-300/10 border border-purple-300/30',
    error: 'bg-gradient-to-br from-purple-300/20 to-purple-200/10 border border-purple-200/30',
  }
  return backgrounds[status] || 'bg-purple-600/10 border border-purple-500/20'
}

const getActionText = (status: string) => {
  const texts: Record<string, string> = {
    success: 'Skipped (already available)',
    failed: 'Failed to process',
    not_found: 'Not found in database',
    error: 'Error during processing',
  }
  return texts[status] || 'Processed'
}

const loadMore = () => {
  // Implement load more functionality if needed
  console.log('Load more clicked')
}

// Lifecycle
onMounted(() => {
  fetchActivities()
})

// Auto-refresh every 30 seconds
useSmartPolling(fetchActivities, 30000)
</script>

// listsync-web/src/components/dashboard/recent-activity.tsx
"use client"

import { useQuery } from "@tanstack/react-query"
import { formatRelativeTime, truncateText } from "@/lib/utils"
import { CheckCircle, XCircle, Clock, ExternalLink, SkipForward, ChevronLeft, ChevronRight, Activity } from "lucide-react"
import { useEffect, useState } from "react"

interface RecentActivityItem {
  title: string
  status: "available" | "not_found" | "requested" | "skipped"
  status_text: string
  timestamp: string
  position: number
  total: number
}

interface RecentActivityResponse {
  items: RecentActivityItem[]
  total_items: number
  page: number
  limit: number
  total_pages: number
  has_next: boolean
  has_prev: boolean
  log_file_used?: string
  error?: string
}

export function RecentActivity() {
  const [mounted, setMounted] = useState(false)
  const [currentPage, setCurrentPage] = useState(1)

  useEffect(() => {
    setMounted(true)
  }, [])

  const { data: activityData, isLoading, error } = useQuery({
    queryKey: ["recent-activity", currentPage],
    queryFn: async (): Promise<RecentActivityResponse> => {
      const response = await fetch(`/api/recent-activity?page=${currentPage}&limit=6&media_only=true`)
      if (!response.ok) {
        throw new Error("Failed to fetch recent activity")
      }
      return response.json()
    },
    refetchInterval: 30000, // Refresh every 30 seconds
    enabled: mounted, // Only run query after component is mounted
  })

  if (!mounted) {
    return (
      <div className="glass-card p-6 w-full h-full">
        <div className="animate-pulse h-full flex flex-col">
          <div className="h-6 bg-white/10 rounded w-1/3 mb-6"></div>
          <div className="space-y-3 flex-1">
            {[...Array(4)].map((_, i) => (
              <div key={i} className="bg-white/5 h-16 rounded-lg"></div>
            ))}
          </div>
        </div>
      </div>
    )
  }

  if (isLoading) {
    return (
      <div className="glass-card p-6 w-full h-full">
        <div className="animate-pulse h-full flex flex-col">
          <div className="h-6 bg-white/10 rounded w-1/3 mb-6"></div>
          <div className="space-y-3 flex-1">
            {[...Array(4)].map((_, i) => (
              <div key={i} className="bg-white/5 h-16 rounded-lg"></div>
            ))}
          </div>
        </div>
      </div>
    )
  }

  const items = activityData?.items || []
  const hasError = activityData?.error || error?.message
  const totalPages = activityData?.total_pages || 0
  const totalItems = activityData?.total_items || 0

  const handlePrevPage = () => {
    if (activityData?.has_prev) {
      setCurrentPage(prev => prev - 1)
    }
  }

  const handleNextPage = () => {
    if (activityData?.has_next) {
      setCurrentPage(prev => prev + 1)
    }
  }

  const getStatusIcon = (status: string) => {
    switch (status) {
      case "available":
        return (
          <div className="p-2 bg-purple-600/20 border border-purple-500/30 rounded-lg">
            <CheckCircle className="h-4 w-4 text-purple-300" />
          </div>
        )
      case "not_found":
        return (
          <div className="p-2 bg-red-600/20 border border-red-500/30 rounded-lg">
            <XCircle className="h-4 w-4 text-red-300" />
          </div>
        )
      case "requested":
        return (
          <div className="p-2 bg-purple-600/20 border border-purple-500/30 rounded-lg">
            <CheckCircle className="h-4 w-4 text-purple-300" />
          </div>
        )
      case "skipped":
        return (
          <div className="p-2 bg-gray-600/20 border border-gray-500/30 rounded-lg">
            <SkipForward className="h-4 w-4 text-gray-300" />
          </div>
        )
      default:
        return (
          <div className="p-2 bg-gray-600/20 border border-gray-500/30 rounded-lg">
            <Clock className="h-4 w-4 text-gray-300" />
          </div>
        )
    }
  }

  const getStatusColor = (status: string) => {
    switch (status) {
      case "available":
        return "bg-purple-500/20 text-purple-300 border border-purple-500/30"
      case "not_found":
        return "bg-red-500/20 text-red-300 border border-red-500/30"
      case "requested":
        return "bg-purple-500/20 text-purple-300 border border-purple-500/30"
      case "skipped":
        return "bg-gray-500/20 text-gray-300 border border-gray-500/30"
      default:
        return "bg-gray-500/20 text-gray-300 border border-gray-500/30"
    }
  }

  const formatTime = (timestamp: string) => {
    if (!timestamp) return "Unknown time"
    
    try {
      const date = new Date(timestamp)
      const now = new Date()
      const diffInMinutes = Math.floor((now.getTime() - date.getTime()) / (1000 * 60))
      
      if (diffInMinutes < 1) return "Just now"
      if (diffInMinutes < 60) return `${diffInMinutes}m ago`
      
      const diffInHours = Math.floor(diffInMinutes / 60)
      if (diffInHours < 24) return `${diffInHours}h ago`
      
      const diffInDays = Math.floor(diffInHours / 24)
      return `${diffInDays}d ago`
    } catch {
      return "Unknown time"
    }
  }

  return (
    <div className="glass-card p-6 w-full flex flex-col h-full">
      <div className="flex items-center justify-between mb-6 flex-wrap gap-4">
        <div className="min-w-0 flex-1">
          <h3 className="text-2xl font-bold text-white mb-2 titillium-web-bold">
            Recent Activity
          </h3>
          <p className="text-base titillium-web-light" style={{ color: 'rgba(255, 255, 255, 0.7)' }}>
            Latest items
          </p>
        </div>
        {totalItems > 0 && (
          <div className="flex items-center gap-3 px-4 py-2 glass-card flex-shrink-0">
            <Activity className="h-5 w-5" style={{ color: '#9d34da' }} />
            <div className="text-right">
              <div className="text-lg font-bold text-white titillium-web-semibold">
                {totalItems}
              </div>
              <div className="text-xs titillium-web-light" style={{ color: 'rgba(255, 255, 255, 0.7)' }}>recent items</div>
            </div>
          </div>
        )}
      </div>

      {hasError ? (
        <div className="text-center py-8 text-red-300/70 flex-1 flex flex-col justify-center min-h-0">
          <div className="text-sm titillium-web-regular">Error loading activity</div>
          <div className="text-xs titillium-web-light mt-1">{hasError}</div>
          {activityData?.log_file_used && (
            <div className="text-xs titillium-web-light mt-1">
              Attempted to read from: {activityData.log_file_used}
            </div>
          )}
        </div>
      ) : items.length === 0 ? (
        <div className="text-center py-8 text-purple-200/70 flex-1 flex flex-col justify-center min-h-0">
          <div className="text-sm titillium-web-regular">No recent activity</div>
          <div className="text-xs titillium-web-light mt-1">Items will appear here after syncing</div>
        </div>
      ) : (
        <>
          <div className="space-y-4 flex-1 min-h-0 overflow-y-auto">
            {items.slice(0, 4).map((item, index) => (
              <div key={`${item.title}-${item.position}-${index}`} className="flex items-center gap-3 p-4 bg-white/5 hover:bg-white/10 transition-colors rounded-lg border border-white/10">
                <div className="flex-shrink-0">
                  {getStatusIcon(item.status)}
                </div>
                
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-2">
                    <span className="font-medium text-white truncate titillium-web-semibold text-sm">
                      {truncateText(item.title, 25)}
                    </span>
                  </div>
                  
                  <div className="flex items-center gap-2">
                    <span className={`inline-flex items-center px-2 py-1 rounded-full text-xs font-medium titillium-web-semibold ${getStatusColor(item.status)}`}>
                      {item.status_text}
                    </span>
                    
                    <span className="text-xs text-white/50 titillium-web-light">
                      {formatTime(item.timestamp)}
                    </span>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {totalPages > 1 && (
            <div className="mt-6 pt-4 border-t border-white/10 flex-shrink-0">
              <div className="flex items-center justify-between">
                <button
                  onClick={handlePrevPage}
                  disabled={!activityData?.has_prev}
                  className={`flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors titillium-web-semibold ${
                    activityData?.has_prev
                      ? 'text-purple-300 hover:text-purple-100 hover:bg-white/10 border border-purple-500/30'
                      : 'text-gray-400 cursor-not-allowed border border-gray-500/30'
                  }`}
                >
                  <ChevronLeft className="h-3 w-3" />
                  Prev
                </button>

                <div className="flex items-center gap-1">
                  <span className="text-xs text-white/60 titillium-web-regular">
                    {currentPage}/{totalPages}
                  </span>
                </div>

                <button
                  onClick={handleNextPage}
                  disabled={!activityData?.has_next}
                  className={`flex items-center gap-1 px-3 py-1.5 rounded-lg text-xs font-medium transition-colors titillium-web-semibold ${
                    activityData?.has_next
                      ? 'text-purple-300 hover:text-purple-100 hover:bg-white/10 border border-purple-500/30'
                      : 'text-gray-400 cursor-not-allowed border border-gray-500/30'
                  }`}
                >
                  Next
                  <ChevronRight className="h-3 w-3" />
                </button>
              </div>
            </div>
          )}
        </>
      )}
    </div>
  )
}
