// listsync-web/src/components/ui/tooltip.tsx
"use client"

import { useState, useRef, useEffect } from "react"
import { Portal } from "./portal"

interface TooltipProps {
  children: React.ReactNode
  content: React.ReactNode
  side?: "top" | "bottom" | "left" | "right"
  align?: "start" | "center" | "end"
  delayDuration?: number
  className?: string
}

export function Tooltip({ 
  children, 
  content, 
  side = "top", 
  align = "center", 
  delayDuration = 200,
  className = ""
}: TooltipProps) {
  const [isVisible, setIsVisible] = useState(false)
  const [position, setPosition] = useState({ x: 0, y: 0 })
  const triggerRef = useRef<HTMLDivElement>(null)
  const timeoutRef = useRef<NodeJS.Timeout | null>(null)

  const updatePosition = () => {
    if (!triggerRef.current) return

    const rect = triggerRef.current.getBoundingClientRect()
    const scrollX = window.pageXOffset || document.documentElement.scrollLeft
    const scrollY = window.pageYOffset || document.documentElement.scrollTop

    let x = 0
    let y = 0

    // Calculate position based on side
    switch (side) {
      case "top":
        x = rect.left + scrollX + (align === "start" ? 0 : align === "end" ? rect.width : rect.width / 2)
        y = rect.top + scrollY - 8 // 8px offset for arrow
        break
      case "bottom":
        x = rect.left + scrollX + (align === "start" ? 0 : align === "end" ? rect.width : rect.width / 2)
        y = rect.bottom + scrollY + 8 // 8px offset for arrow
        break
      case "left":
        x = rect.left + scrollX - 8 // 8px offset for arrow
        y = rect.top + scrollY + (align === "start" ? 0 : align === "end" ? rect.height : rect.height / 2)
        break
      case "right":
        x = rect.right + scrollX + 8 // 8px offset for arrow
        y = rect.top + scrollY + (align === "start" ? 0 : align === "end" ? rect.height : rect.height / 2)
        break
    }

    setPosition({ x, y })
  }

  const handleMouseEnter = () => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current)
    }
    timeoutRef.current = setTimeout(() => {
      updatePosition()
      setIsVisible(true)
    }, delayDuration)
  }

  const handleMouseLeave = () => {
    if (timeoutRef.current) {
      clearTimeout(timeoutRef.current)
    }
    setIsVisible(false)
  }

  useEffect(() => {
    if (isVisible) {
      const handleScroll = () => updatePosition()
      const handleResize = () => updatePosition()
      
      window.addEventListener('scroll', handleScroll, true)
      window.addEventListener('resize', handleResize)
      
      return () => {
        window.removeEventListener('scroll', handleScroll, true)
        window.removeEventListener('resize', handleResize)
      }
    }
  }, [isVisible])

  useEffect(() => {
    return () => {
      if (timeoutRef.current) {
        clearTimeout(timeoutRef.current)
      }
    }
  }, [])

  const getTransformOrigin = () => {
    switch (side) {
      case "top":
        return align === "start" ? "bottom left" : align === "end" ? "bottom right" : "bottom center"
      case "bottom":
        return align === "start" ? "top left" : align === "end" ? "top right" : "top center"
      case "left":
        return align === "start" ? "top right" : align === "end" ? "bottom right" : "center right"
      case "right":
        return align === "start" ? "top left" : align === "end" ? "bottom left" : "center left"
    }
  }

  const getTransform = () => {
    let transform = ""
    
    switch (side) {
      case "top":
        transform += "translateY(-100%)"
        break
      case "bottom":
        transform += "translateY(0%)"
        break
      case "left":
        transform += "translateX(-100%)"
        break
      case "right":
        transform += "translateX(0%)"
        break
    }

    if (side === "top" || side === "bottom") {
      if (align === "center") transform += " translateX(-50%)"
      else if (align === "end") transform += " translateX(-100%)"
    } else {
      if (align === "center") transform += " translateY(-50%)"
      else if (align === "end") transform += " translateY(-100%)"
    }

    return transform
  }

  return (
    <>
      <div
        ref={triggerRef}
        onMouseEnter={handleMouseEnter}
        onMouseLeave={handleMouseLeave}
        className="inline-block"
      >
        {children}
      </div>
      
      {isVisible && (
        <Portal>
          <div
            className={`
              fixed pointer-events-none z-[2147483647]
              px-3 py-2 bg-black/95 text-white text-xs rounded-lg shadow-xl
              border border-white/20 whitespace-nowrap
              transition-all duration-200 ease-out
              ${className}
            `}
            style={{
              left: position.x,
              top: position.y,
              transform: getTransform(),
              transformOrigin: getTransformOrigin(),
            }}
          >
            {content}
            
            {/* Arrow */}
            <div
              className="absolute w-0 h-0"
              style={{
                ...(side === "top" && {
                  top: "100%",
                  left: align === "start" ? "12px" : align === "end" ? "calc(100% - 12px)" : "50%",
                  transform: align === "center" ? "translateX(-50%)" : undefined,
                  borderLeft: "4px solid transparent",
                  borderRight: "4px solid transparent",
                  borderTop: "4px solid rgba(0, 0, 0, 0.95)",
                }),
                ...(side === "bottom" && {
                  bottom: "100%",
                  left: align === "start" ? "12px" : align === "end" ? "calc(100% - 12px)" : "50%",
                  transform: align === "center" ? "translateX(-50%)" : undefined,
                  borderLeft: "4px solid transparent",
                  borderRight: "4px solid transparent",
                  borderBottom: "4px solid rgba(0, 0, 0, 0.95)",
                }),
                ...(side === "left" && {
                  left: "100%",
                  top: align === "start" ? "12px" : align === "end" ? "calc(100% - 12px)" : "50%",
                  transform: align === "center" ? "translateY(-50%)" : undefined,
                  borderTop: "4px solid transparent",
                  borderBottom: "4px solid transparent",
                  borderLeft: "4px solid rgba(0, 0, 0, 0.95)",
                }),
                ...(side === "right" && {
                  right: "100%",
                  top: align === "start" ? "12px" : align === "end" ? "calc(100% - 12px)" : "50%",
                  transform: align === "center" ? "translateY(-50%)" : undefined,
                  borderTop: "4px solid transparent",
                  borderBottom: "4px solid transparent",
                  borderRight: "4px solid rgba(0, 0, 0, 0.95)",
                }),
              }}
            />
          </div>
        </Portal>
      )}
    </>
  )
}

// listsync-nuxt/components/ui/Tooltip.vue
<template>
  <div
    ref="triggerRef"
    class="inline-block"
    @mouseenter="showTooltip"
    @mouseleave="hideTooltip"
    @focus="showTooltip"
    @blur="hideTooltip"
  >
    <slot />
    
    <Teleport to="body">
      <Transition name="tooltip">
        <div
          v-if="isVisible && content"
          ref="tooltipRef"
          :class="tooltipClasses"
          :style="tooltipStyle"
          role="tooltip"
        >
          {{ content }}
          <div :class="arrowClasses" :style="arrowStyle" />
        </div>
      </Transition>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
interface Props {
  content?: string
  placement?: 'top' | 'bottom' | 'left' | 'right'
  delay?: number
}

const props = withDefaults(defineProps<Props>(), {
  placement: 'top',
  delay: 200,
})

const triggerRef = ref<HTMLElement | null>(null)
const tooltipRef = ref<HTMLElement | null>(null)
const isVisible = ref(false)
const tooltipStyle = ref({})
const arrowStyle = ref({})
let showTimeout: NodeJS.Timeout | null = null

const showTooltip = () => {
  if (showTimeout) clearTimeout(showTimeout)
  
  showTimeout = setTimeout(() => {
    isVisible.value = true
    nextTick(() => {
      updatePosition()
    })
  }, props.delay)
}

const hideTooltip = () => {
  if (showTimeout) {
    clearTimeout(showTimeout)
    showTimeout = null
  }
  isVisible.value = false
}

const updatePosition = () => {
  if (!triggerRef.value || !tooltipRef.value) return

  const triggerRect = triggerRef.value.getBoundingClientRect()
  const tooltipRect = tooltipRef.value.getBoundingClientRect()
  const spacing = 8

  let top = 0
  let left = 0

  switch (props.placement) {
    case 'top':
      top = triggerRect.top - tooltipRect.height - spacing
      left = triggerRect.left + (triggerRect.width - tooltipRect.width) / 2
      break
    
    case 'bottom':
      top = triggerRect.bottom + spacing
      left = triggerRect.left + (triggerRect.width - tooltipRect.width) / 2
      break
    
    case 'left':
      top = triggerRect.top + (triggerRect.height - tooltipRect.height) / 2
      left = triggerRect.left - tooltipRect.width - spacing
      break
    
    case 'right':
      top = triggerRect.top + (triggerRect.height - tooltipRect.height) / 2
      left = triggerRect.right + spacing
      break
  }

  // Ensure tooltip stays within viewport
  const viewportWidth = window.innerWidth
  const viewportHeight = window.innerHeight

  if (left < spacing) left = spacing
  if (left + tooltipRect.width > viewportWidth - spacing) {
    left = viewportWidth - tooltipRect.width - spacing
  }
  
  if (top < spacing) top = spacing
  if (top + tooltipRect.height > viewportHeight - spacing) {
    top = viewportHeight - tooltipRect.height - spacing
  }

  tooltipStyle.value = {
    top: `${top}px`,
    left: `${left}px`,
  }

  // Arrow positioning
  const arrowSize = 6
  switch (props.placement) {
    case 'top':
      arrowStyle.value = {
        top: '100%',
        left: '50%',
        transform: 'translateX(-50%)',
        borderLeft: `${arrowSize}px solid transparent`,
        borderRight: `${arrowSize}px solid transparent`,
        borderTop: `${arrowSize}px solid rgba(157, 52, 218, 0.95)`,
      }
      break
    
    case 'bottom':
      arrowStyle.value = {
        bottom: '100%',
        left: '50%',
        transform: 'translateX(-50%)',
        borderLeft: `${arrowSize}px solid transparent`,
        borderRight: `${arrowSize}px solid transparent`,
        borderBottom: `${arrowSize}px solid rgba(157, 52, 218, 0.95)`,
      }
      break
    
    case 'left':
      arrowStyle.value = {
        left: '100%',
        top: '50%',
        transform: 'translateY(-50%)',
        borderTop: `${arrowSize}px solid transparent`,
        borderBottom: `${arrowSize}px solid transparent`,
        borderLeft: `${arrowSize}px solid rgba(157, 52, 218, 0.95)`,
      }
      break
    
    case 'right':
      arrowStyle.value = {
        right: '100%',
        top: '50%',
        transform: 'translateY(-50%)',
        borderTop: `${arrowSize}px solid transparent`,
        borderBottom: `${arrowSize}px solid transparent`,
        borderRight: `${arrowSize}px solid rgba(157, 52, 218, 0.95)`,
      }
      break
  }
}

const tooltipClasses = computed(() => {
  return [
    'fixed z-[9999] px-3 py-2 text-sm font-medium text-white',
    'rounded-lg shadow-lg',
    'bg-purple-600/95 backdrop-blur-sm',
    'pointer-events-none',
    'max-w-xs',
  ].join(' ')
})

const arrowClasses = 'absolute w-0 h-0'

onUnmounted(() => {
  if (showTimeout) clearTimeout(showTimeout)
})
</script>

<style scoped>
.tooltip-enter-active,
.tooltip-leave-active {
  transition: opacity 0.15s ease;
}

.tooltip-enter-from,
.tooltip-leave-to {
  opacity: 0;
}
</style>
